// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKdxKCXc0A7VUSCQb5uRz9dZ1xobfPwaY',
    appId: '1:3133951958:web:e370622bd349541cac5e77',
    messagingSenderId: '3133951958',
    projectId: 'flic-d579d',
    authDomain: 'flic-d579d.firebaseapp.com',
    databaseURL: 'https://flic-d579d-default-rtdb.firebaseio.com',
    storageBucket: 'flic-d579d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZu1-k-8CISnZZTUvdrR-l_k1ASDmfqjk',
    appId: '1:3133951958:android:02ae2c5695ab4ebeac5e77',
    messagingSenderId: '3133951958',
    projectId: 'flic-d579d',
    databaseURL: 'https://flic-d579d-default-rtdb.firebaseio.com',
    storageBucket: 'flic-d579d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOuJRY85rlCgDlIRMARweKmPgNJkOj6rw',
    appId: '1:3133951958:ios:856bafce9b606613ac5e77',
    messagingSenderId: '3133951958',
    projectId: 'flic-d579d',
    databaseURL: 'https://flic-d579d-default-rtdb.firebaseio.com',
    storageBucket: 'flic-d579d.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOuJRY85rlCgDlIRMARweKmPgNJkOj6rw',
    appId: '1:3133951958:ios:856bafce9b606613ac5e77',
    messagingSenderId: '3133951958',
    projectId: 'flic-d579d',
    databaseURL: 'https://flic-d579d-default-rtdb.firebaseio.com',
    storageBucket: 'flic-d579d.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKdxKCXc0A7VUSCQb5uRz9dZ1xobfPwaY',
    appId: '1:3133951958:web:27eb218aa2ef6926ac5e77',
    messagingSenderId: '3133951958',
    projectId: 'flic-d579d',
    authDomain: 'flic-d579d.firebaseapp.com',
    databaseURL: 'https://flic-d579d-default-rtdb.firebaseio.com',
    storageBucket: 'flic-d579d.firebasestorage.app',
  );
}
