name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 0) 리포 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1) (선택) Java: 일부 플러터/플러그인에서 필요할 수 있음
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Remove preinstalled Flutter
        run: sudo rm -rf /opt/hostedtoolcache/flutter


      # 2) Flutter 설치 (Dart 3.7.2 포함 버전으로 고정) + 캐시 비활성화
      - name: Set up Flutter (stable 3.27.2)
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.27.2"
          cache: false

      # 3) (중요) 실제 설치된 Flutter/Dart 버전 확인
      - name: Show Flutter & Dart versions
        run: |
          flutter --version
          dart --version

      # 4) 웹 타깃 프리캐시 (웹 빌드 시 권장)
      - name: Precache web artifacts
        run: flutter precache --web

      # 5) 의존성 설치
      - name: Flutter pub get
        run: flutter pub get

      # 6) 깨끗한 빌드
      - name: Clean build
        run: flutter clean

      # 7) Flutter 웹 빌드 (산출물: build/web)
      - name: Build Flutter web (release)
        run: flutter build web --release

      # 8) Firebase Hosting 배포
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLIC_D579D }}
          channelId: live
          projectId: flic-d579d
